In [16]:
import pandas as pd
import numpy as np

crime_anal_station = pd.read_csv('../data2/02. crime_in_Seoul_raw.csv', index_col=0, encoding='utf-8')      # index_col : '구분'을 인덱스 컬럼으로 설정
crime_anal_station.head()

,강간검거,강간발생,강도검거,강도발생,살인검거,살인발생,절도검거,절도발생,폭력검거,폭력발생,구별,lat,lng
구분,,,,,,,,,,,,,
강남,269.0,339.0,26.0,24.0,3.0,3.0,1129.0,2438.0,2096.0,2336.0,강남구,37.509435,127.066958
강동,152.0,160.0,13.0,14.0,5.0,4.0,902.0,1754.0,2201.0,2530.0,강동구,37.528511,127.126822
강북,159.0,217.0,4.0,5.0,6.0,7.0,672.0,1222.0,2482.0,2778.0,강북구,37.637388,127.027324
강서,239.0,275.0,10.0,10.0,10.0,9.0,1070.0,1952.0,2768.0,3204.0,양천구,37.539783,126.829997
관악,264.0,322.0,10.0,12.0,7.0,6.0,937.0,2103.0,2707.0,3235.0,관악구,37.474379,126.950975

In [17]:
crime_anal_gu = pd.pivot_table(crime_anal_station, index='구별', aggfunc=np.sum)

del crime_anal_gu['lat']
crime_anal_gu.drop('lng', axis=1, inplace=True)
crime_anal_gu.head()

      강간검거   강간발생  강도검거  강도발생  살인검거  살인발생    절도검거    절도발생    폭력검거    폭력발생
구별
강남구  413.0  516.0  42.0  39.0   5.0   5.0  1918.0  3587.0  3527.0  4002.0
강동구  152.0  160.0  13.0  14.0   5.0   4.0   902.0  1754.0  2201.0  2530.0
강북구  159.0  217.0   4.0   5.0   6.0   7.0   672.0  1222.0  2482.0  2778.0
관악구  407.0  497.0  17.0  19.0  13.0  12.0  1591.0  3367.0  4653.0  5428.0
광진구  234.0  279.0   6.0  11.0   4.0   4.0  1057.0  2636.0  2011.0  2392.0

In [18]:
crime_anal_gu['강도검거'] / crime_anal_gu['강도발생']

구별
강남구     1.076923
강동구     0.928571
강북구     0.800000
관악구     0.894737
광진구     0.545455
구로구     1.300000
노원구     1.500000
도봉구     1.000000
동대문구    1.200000
동작구     1.000000
마포구     1.750000
서대문구    0.800000
서초구     0.769231
성동구     1.666667
성북구     1.000000
송파구     0.800000
양천구     1.000000
영등포구    0.736842
용산구     1.111111
은평구     0.777778
종로구     0.750000
중구      0.875000
중랑구     1.000000
dtype: float64

In [19]:
crime_anal_gu[['강도검거','살인검거']].div(crime_anal_gu['강도발생'], axis=0).head(3)

         강도검거      살인검거
구별
강남구  1.076923  0.128205
강동구  0.928571  0.357143
강북구  0.800000  1.200000

In [20]:
num = ['강간검거','강도검거','살인검거','절도검거','폭력검거']
den = ['강간발생','강도발생','살인발생','절도발생','폭력발생']

crime_anal_gu[num].div(crime_anal_gu[den].values).head()

         강간검거      강도검거      살인검거      절도검거      폭력검거
구별
강남구  0.800388  1.076923  1.000000  0.534709  0.881309
강동구  0.950000  0.928571  1.250000  0.514253  0.869960
강북구  0.732719  0.800000  0.857143  0.549918  0.893449
관악구  0.818913  0.894737  1.083333  0.472527  0.857222
광진구  0.838710  0.545455  1.000000  0.400986  0.840719

In [21]:
target = ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']

num = ['강간검거','강도검거','살인검거','절도검거','폭력검거']
den = ['강간발생','강도발생','살인발생','절도발생','폭력발생']

crime_anal_gu[target]  = crime_anal_gu[num].div(crime_anal_gu[den].values) * 100
crime_anal_gu.head()

,강간검거,강간발생,강도검거,강도발생,살인검거,살인발생,절도검거,절도발생,폭력검거,폭력발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,,,,,
강남구,413.0,516.0,42.0,39.0,5.0,5.0,1918.0,3587.0,3527.0,4002.0,80.038760,107.692308,100.000000,53.470867,88.130935
강동구,152.0,160.0,13.0,14.0,5.0,4.0,902.0,1754.0,2201.0,2530.0,95.000000,92.857143,125.000000,51.425314,86.996047
강북구,159.0,217.0,4.0,5.0,6.0,7.0,672.0,1222.0,2482.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
관악구,407.0,497.0,17.0,19.0,13.0,12.0,1591.0,3367.0,4653.0,5428.0,81.891348,89.473684,108.333333,47.252747,85.722181
광진구,234.0,279.0,6.0,11.0,4.0,4.0,1057.0,2636.0,2011.0,2392.0,83.870968,54.545455,100.000000,40.098634,84.071906

In [22]:
# 필요없는 컬럼 제거
del crime_anal_gu['강간검거']
del crime_anal_gu['강도검거']
crime_anal_gu.drop(['살인검거','절도검거','폭력검거'], axis=1, inplace=True)

crime_anal_gu.head()

,강간발생,강도발생,살인발생,절도발생,폭력발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,516.0,39.0,5.0,3587.0,4002.0,80.038760,107.692308,100.000000,53.470867,88.130935
강동구,160.0,14.0,4.0,1754.0,2530.0,95.000000,92.857143,125.000000,51.425314,86.996047
강북구,217.0,5.0,7.0,1222.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
관악구,497.0,19.0,12.0,3367.0,5428.0,81.891348,89.473684,108.333333,47.252747,85.722181
광진구,279.0,11.0,4.0,2636.0,2392.0,83.870968,54.545455,100.000000,40.098634,84.071906

In [26]:
# 100보다 큰 숫자를 찾아서 바꾸기
crime_anal_gu[crime_anal_gu[target] > 100] = 100
crime_anal_gu.head()

,강간발생,강도발생,살인발생,절도발생,폭력발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,516.0,39.0,5.0,3587.0,4002.0,80.038760,100.000000,100.000000,53.470867,88.130935
강동구,160.0,14.0,4.0,1754.0,2530.0,95.000000,92.857143,100.000000,51.425314,86.996047
강북구,217.0,5.0,7.0,1222.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
관악구,497.0,19.0,12.0,3367.0,5428.0,81.891348,89.473684,100.000000,47.252747,85.722181
광진구,279.0,11.0,4.0,2636.0,2392.0,83.870968,54.545455,100.000000,40.098634,84.071906

In [28]:
# 컬럼 이름 변경
crime_anal_gu.rename(columns={'강간발생' : '강간', '살인발생' : '살인', '절도발생':'절도', '폭력발생':'폭력', '강도발생':'강도'},
inplace=True)
crime_anal_gu.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,516.0,39.0,5.0,3587.0,4002.0,80.038760,100.000000,100.000000,53.470867,88.130935
강동구,160.0,14.0,4.0,1754.0,2530.0,95.000000,92.857143,100.000000,51.425314,86.996047
강북구,217.0,5.0,7.0,1222.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
관악구,497.0,19.0,12.0,3367.0,5428.0,81.891348,89.473684,100.000000,47.252747,85.722181
광진구,279.0,11.0,4.0,2636.0,2392.0,83.870968,54.545455,100.000000,40.098634,84.071906

---
# 데이터 정규화

In [30]:
# 정규화 : 최고값은 1, 최소값은 0
crime_anal_gu['강도']/crime_anal_gu['강도'].max()

구별
강남구     1.000000
강동구     0.358974
강북구     0.128205
관악구     0.487179
광진구     0.282051
구로구     0.256410
노원구     0.153846
도봉구     0.128205
동대문구    0.256410
동작구     0.179487
마포구     0.102564
서대문구    0.128205
서초구     0.333333
성동구     0.076923
성북구     0.205128
송파구     0.384615
양천구     0.435897
영등포구    0.487179
용산구     0.230769
은평구     0.230769
종로구     0.307692
중구      0.205128
중랑구     0.358974
Name: 강도, dtype: float64

In [31]:
col = ['강간'	,'강도'	,'살인',	'절도',	'폭력']
crime_anal_norm = crime_anal_gu[col] / crime_anal_gu[col].max()
crime_anal_norm.head()

           강간        강도        살인        절도        폭력
구별
강남구  1.000000  1.000000  0.357143  0.977118  0.733773
강동구  0.310078  0.358974  0.285714  0.477799  0.463880
강북구  0.420543  0.128205  0.500000  0.332879  0.509351
관악구  0.963178  0.487179  0.857143  0.917189  0.995233
광진구  0.540698  0.282051  0.285714  0.718060  0.438577

In [32]:
crime_anal_gu.head(1)

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,516.0,39.0,5.0,3587.0,4002.0,80.03876,100.0,100.0,53.470867,88.130935

In [33]:
# 검거율 추가
col2 = ['강간검거율'	,'강도검거율'	,'살인검거율'	,'절도검거율'	,'폭력검거율']
crime_anal_norm[col2] = crime_anal_gu[col2]
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,1.000000,1.000000,0.357143,0.977118,0.733773,80.038760,100.000000,100.000000,53.470867,88.130935
강동구,0.310078,0.358974,0.285714,0.477799,0.463880,95.000000,92.857143,100.000000,51.425314,86.996047
강북구,0.420543,0.128205,0.500000,0.332879,0.509351,73.271889,80.000000,85.714286,54.991817,89.344852
관악구,0.963178,0.487179,0.857143,0.917189,0.995233,81.891348,89.473684,100.000000,47.252747,85.722181
광진구,0.540698,0.282051,0.285714,0.718060,0.438577,83.870968,54.545455,100.000000,40.098634,84.071906

In [35]:
# 구별 CCTV 자료에서 인구수와 CCTV 수 추가
result_cctv = pd.read_csv('../data/01. CCTV_result.csv', index_col='구별', encoding='utf-8')
result_cctv.head()

,소계,최근증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율,CCTV비율,오차
구별,,,,,,,,,,
강남구,3238,150.619195,561052,556164,4888,65060,0.871220,11.596073,0.577130,1549.200326
강동구,1010,166.490765,440359,436223,4136,56161,0.939234,12.753458,0.229358,-544.642322
강북구,831,125.203252,328002,324479,3523,56530,1.074079,17.234651,0.253352,-598.750923
강서구,911,134.793814,608255,601691,6564,76032,1.079153,12.500021,0.149773,-830.268578
관악구,2109,149.290780,520929,503297,17632,70046,3.384722,13.446362,0.404854,464.799395

In [36]:
crime_anal_norm[['인구수','CCTV']] = result_cctv[['인구수','소계']]
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV
구별,,,,,,,,,,,,
강남구,1.000000,1.000000,0.357143,0.977118,0.733773,80.038760,100.000000,100.000000,53.470867,88.130935,561052,3238
강동구,0.310078,0.358974,0.285714,0.477799,0.463880,95.000000,92.857143,100.000000,51.425314,86.996047,440359,1010
강북구,0.420543,0.128205,0.500000,0.332879,0.509351,73.271889,80.000000,85.714286,54.991817,89.344852,328002,831
관악구,0.963178,0.487179,0.857143,0.917189,0.995233,81.891348,89.473684,100.000000,47.252747,85.722181,520929,2109
광진구,0.540698,0.282051,0.285714,0.718060,0.438577,83.870968,54.545455,100.000000,40.098634,84.071906,372298,878

In [37]:
# 정규화된 범죄발생 건수 전체의 평균을 구해서 범죄 컬럼 대표값으로 사용
col=['강간','강도','살인','절도','폭력']
crime_anal_norm['범죄'] = np.mean(crime_anal_norm[col], axis=1)
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄
구별,,,,,,,,,,,,,
강남구,1.000000,1.000000,0.357143,0.977118,0.733773,80.038760,100.000000,100.000000,53.470867,88.130935,561052,3238,0.813607
강동구,0.310078,0.358974,0.285714,0.477799,0.463880,95.000000,92.857143,100.000000,51.425314,86.996047,440359,1010,0.379289
강북구,0.420543,0.128205,0.500000,0.332879,0.509351,73.271889,80.000000,85.714286,54.991817,89.344852,328002,831,0.378196
관악구,0.963178,0.487179,0.857143,0.917189,0.995233,81.891348,89.473684,100.000000,47.252747,85.722181,520929,2109,0.843984
광진구,0.540698,0.282051,0.285714,0.718060,0.438577,83.870968,54.545455,100.000000,40.098634,84.071906,372298,878,0.453020

In [46]:
# np.mean() 활용
t = '1.000000	1.000000	0.357143	0.977118	0.733773'
t = list(map(float, t.split()))
np.mean(t, axis=0)

0.8136068

In [47]:
# 검거율의 평균을 구해서 검거 컬럼의 대표값으로 사용
col = ['강간검거율',	'강도검거율'	,'살인검거율'	,'절도검거율'	,'폭력검거율']
crime_anal_norm['검거'] = np.mean(crime_anal_norm[col], axis=1)
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄,검거
구별,,,,,,,,,,,,,,
강남구,1.000000,1.000000,0.357143,0.977118,0.733773,80.038760,100.000000,100.000000,53.470867,88.130935,561052,3238,0.813607,84.328112
강동구,0.310078,0.358974,0.285714,0.477799,0.463880,95.000000,92.857143,100.000000,51.425314,86.996047,440359,1010,0.379289,85.255701
강북구,0.420543,0.128205,0.500000,0.332879,0.509351,73.271889,80.000000,85.714286,54.991817,89.344852,328002,831,0.378196,76.664569
관악구,0.963178,0.487179,0.857143,0.917189,0.995233,81.891348,89.473684,100.000000,47.252747,85.722181,520929,2109,0.843984,80.867992
광진구,0.540698,0.282051,0.285714,0.718060,0.438577,83.870968,54.545455,100.000000,40.098634,84.071906,372298,878,0.453020,72.517393

In [48]:
crime_anal_norm

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄,검거
구별,,,,,,,,,,,,,,
강남구,1.000000,1.000000,0.357143,0.977118,0.733773,80.038760,100.000000,100.000000,53.470867,88.130935,561052,3238,0.813607,84.328112
강동구,0.310078,0.358974,0.285714,0.477799,0.463880,95.000000,92.857143,100.000000,51.425314,86.996047,440359,1010,0.379289,85.255701
강북구,0.420543,0.128205,0.500000,0.332879,0.509351,73.271889,80.000000,85.714286,54.991817,89.344852,328002,831,0.378196,76.664569
관악구,0.963178,0.487179,0.857143,0.917189,0.995233,81.891348,89.473684,100.000000,47.252747,85.722181,520929,2109,0.843984,80.867992
광진구,0.540698,0.282051,0.285714,0.718060,0.438577,83.870968,54.545455,100.000000,40.098634,84.071906,372298,878,0.453020,72.517393
구로구,0.529070,0.256410,0.642857,0.520294,0.580125,66.300366,100.000000,100.000000,45.078534,84.702908,441559,1884,0.505751,79.216362
노원구,0.308140,0.153846,0.357143,0.505857,0.461313,89.308176,100.000000,100.000000,39.849219,84.419714,558075,1566,0.357260,82.715422
도봉구,0.238372,0.128205,0.214286,0.235903,0.264210,98.373984,100.000000,100.000000,56.812933,90.839695,346234,825,0.216195,89.205322
동대문구,0.368217,0.256410,0.357143,0.528466,0.484415,83.157895,100.000000,100.000000,55.206186,89.969720,366011,1870,0.398930,85.666760
동작구,0.629845,0.179487,0.571429,0.333969,0.304547,45.846154,100.000000,75.000000,45.187602,86.935581,408493,1302,0.403855,70.593867
마포구,0.773256,0.102564,0.285714,0.688368,0.538871,80.200501,100.000000,100.000000,37.198259,85.062947,385783,980,0.477755,80.492341
서대문구,0.339147,0.128205,0.428571,0.409425,0.362303,84.000000,80.000000,100.000000,50.033267,83.198381,325028,1254,0.333530,79.446329
서초구,0.829457,0.333333,0.357143,0.600654,0.428676,63.317757,76.923077,100.000000,50.204082,86.783576,445401,2297,0.509853,75.445698
성동구,0.201550,0.076923,0.285714,0.353037,0.296846,75.000000,100.000000,100.000000,69.135802,86.967264,312711,1327,0.242814,86.220613
성북구,0.298450,0.205128,0.285714,0.400436,0.386505,75.974026,100.000000,75.000000,49.319728,86.290323,455407,1651,0.315247,77.316815
송파구,0.453488,0.384615,0.642857,0.692727,0.603044,78.632479,80.000000,88.888889,41.211168,85.375494,671173,1081,0.555346,74.821606
양천구,0.786822,0.435897,1.000000,1.000000,1.000000,85.467980,100.000000,100.000000,49.713974,85.918592,475018,2482,0.844544,84.220109
영등포구,0.689922,0.487179,0.928571,0.637701,0.658783,63.202247,73.684211,100.000000,40.153780,83.690509,402024,1277,0.680431,72.146149
용산구,0.486434,0.230769,0.285714,0.405612,0.437110,85.258964,100.000000,100.000000,40.228341,84.228188,244444,2096,0.369128,81.943099
은평구,0.302326,0.230769,0.428571,0.453827,0.488449,91.025641,77.777778,100.000000,53.421369,86.636637,491202,2108,0.380788,81.772285
종로구,0.461240,0.307692,0.428571,0.528466,0.414925,74.369748,75.000000,33.333333,39.587629,87.361909,164257,1619,0.428179,61.930524
중구,0.383721,0.205128,0.214286,0.585671,0.407957,74.747475,87.500000,100.000000,42.511628,89.707865,134593,1023,0.359353,78.893394
중랑구,0.317829,0.358974,0.571429,0.460637,0.580125,91.463415,100.000000,87.500000,62.211709,85.714286,412780,916,0.457799,85.377882